drop table if exists journey;

create table journey
(
    id           bigint generated by default as identity
        constraint journey_pkey
            primary key,
    arrival      date         not null,
    departure    date         not null,
    route        varchar(255) not null,
    station_from varchar(255) not null,
    station_to   varchar(255) not null
);

alter table journey owner to postgres;

INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Odessa', 'Kiev', '2021-04-05', '2021-04-06', 'Odessa->Kiev');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Odessa', 'Kiev', '2021-04-06', '2021-04-07', 'Odessa->Kiev');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Odessa', 'Kiev', '2021-04-07', '2021-04-08', 'Odessa->Kiev');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Kiev', 'Odessa', '2021-04-05', '2021-04-06', 'Kiev->Odessa');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Kiev', 'Odessa', '2021-04-06', '2021-04-07', 'Kiev->Odessa');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Kiev', 'Odessa', '2021-04-07', '2021-04-08', 'Kiev->Odessa');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Lviv', 'Kiev', '2021-04-05', '2021-04-06', 'Lviv->Kiev');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Lviv', 'Kiev', '2021-04-06', '2021-04-07', 'Lviv->Kiev');
INSERT INTO journey (station_from, station_to, departure, arrival, route) VALUES ('Lviv', 'Kiev', '2021-04-07', '2021-04-08', 'Lviv->Kiev');
